export const POST_FETCH_REQUEST = "POST_FETCH_REQUEST";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";
export const POST_FETCH_FAIL = "POST_FETCH_FAIL";

export const POSTS_FETCH_REQUEST = "POSTS_FETCH_REQUEST";
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_FETCH_FAIL = "POSTS_FETCH_FAIL";
export const POSTS_FETCH_RESET = "POSTS_FETCH_RESET";

export const POSTS_REF_FETCH_REQUEST = "POSTS_REF_FETCH_REQUEST";
export const POSTS_REF_FETCH_SUCCESS = "POSTS_REF_FETCH_SUCCESS";
export const POSTS_REF_FETCH_FAIL = "POSTS_REF_FETCH_FAIL";

export const POSTS_SORT_REQUEST = "POSTS_SORT_REQUEST";
export const POSTS_SORT_SUCCESS = "POSTS_SORT_SUCCESS";
export const POSTS_SORT_FAIL = "POSTS_SORT_FAIL";

export const POSTS_MOST_POPULAR_REQUEST = "POSTS_MOST_POPULAR_REQUEST";
export const POSTS_MOST_POPULAR_SUCCESS = "POSTS_MOST_POPULAR_SUCCESS";
export const POSTS_MOST_POPULAR_FAIL = "POSTS_MOST_POPULAR_FAIL";
